train_dataset:
  dataset:
    name: hsi-folder
    args:
      root_path: /home3/jsg/dataset/Chikusei/train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      augment: true
      sample_q: 2304
  batch_size: 16

val_dataset:
  dataset:
    name: hsi-folder
    args:
      root_path: /home3/jsg/dataset/Chikusei/valid_HR
      first_k: 10
      repeat: 160
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 48
      scale_max: 4
      sample_q: 2304
  batch_size: 16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: SQformer
  args:
    encoder_spec:
      name: swinir-T
      args:
        in_chans: 128
    imnet_spec:
      name: SpectralQuerier
      args:
        hlayers: 1
        nlayers: 3
        hid_dim: 96
        out_dim: 128
        num_heads: 4
        qkv_bias: FALSE
        attn_drop: 0.
        proj_drop: 0.
        expandsion: 4
        mlp_drop: 0.
    feat_unfold: FALSE
    pos_embed: TRUE
    cell_decode: TRUE

optimizer:
  name: adam
  args:
    lr: 2.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [500, 700, 900, 950]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
